# Generated by Django 5.0.6 on 2026-09-09 22:09

from django.db import migrations, models


def mark_existing_users_as_profile_completed(apps, schema_editor):
    """Grandfather clause (Story 3.5): toda conta que ja existir no momento deste deploy nunca
    deve ser pega pelo gate de nome/sobrenome -- so contas novas (criadas depois desta migration,
    via o fluxo de cadastro so-com-email) nascem com profile_completed=False."""
    User = apps.get_model('accounts', 'User')
    User.objects.update(profile_completed=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Nome e sobrenome informados no primeiro login (Story 3.5).', verbose_name='Perfil completo'),
        ),
        migrations.RunPython(mark_existing_users_as_profile_completed, noop_reverse),
    ]
