# Generated by Django 5.0.6 on 2026-09-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=True, help_text='Nome e sobrenome informados no primeiro login (Story 3.5).', verbose_name='Perfil completo'),
        ),
    ]
