# Generated by Django 6.0.5 on 2026-05-08 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número do concurso')),
                ('data_sorteio', models.DateField(blank=True, null=True, verbose_name='Data do sorteio')),
                ('dezenas', models.JSONField(default=list, verbose_name='Dezenas sorteadas')),
                ('dezenas_segundo_sorteio', models.JSONField(blank=True, default=list, verbose_name='Dezenas 2o sorteio')),
                ('trevos_sorteados', models.JSONField(blank=True, default=list, verbose_name='Trevos sorteados')),
                ('valor_estimado_proximo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor estimado próximo')),
                ('proximo_concurso', models.PositiveIntegerField(blank=True, null=True, verbose_name='Próximo concurso')),
                ('dados_completos', models.JSONField(blank=True, null=True, verbose_name='Resposta completa da API')),
                ('cadastrado_manualmente', models.BooleanField(default=False, verbose_name='Cadastrado manualmente')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug_api', models.CharField(help_text='Identificador usado na URL da API. Ex: megasena, lotofacil', max_length=30, verbose_name='Slug API Caixa')),
                ('cor', models.CharField(default='#209869', max_length=7, verbose_name='Cor (hex)')),
                ('qtd_dezenas', models.PositiveIntegerField(verbose_name='Qtd de dezenas por aposta')),
                ('max_numero', models.PositiveIntegerField(verbose_name='Número máximo')),
                ('qtd_trevos', models.PositiveIntegerField(default=0, verbose_name='Qtd de trevos')),
                ('max_trevo', models.PositiveIntegerField(default=0, verbose_name='Trevo máximo')),
                ('aplica_regra_sequencia', models.BooleanField(default=False, help_text='Máx 1 par consecutivo por jogo, intervalo mín. 5 jogos.', verbose_name='Aplica regra de sequência')),
                ('tem_segundo_sorteio', models.BooleanField(default=False, verbose_name='Tem 2o sorteio')),
            ],
            options={
                'verbose_name': 'Tipo de Jogo',
                'verbose_name_plural': 'Tipos de Jogo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='JogoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_concurso', models.PositiveIntegerField(verbose_name='Número do concurso')),
                ('numeros', models.JSONField(default=list, verbose_name='Números apostados')),
                ('trevos', models.JSONField(blank=True, default=list, verbose_name='Trevos apostados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('acertos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Acertos')),
                ('acertos_segundo_sorteio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Acertos 2o sorteio')),
                ('acertos_trevos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Acertos trevos')),
                ('conferido', models.BooleanField(default=False, verbose_name='Conferido')),
                ('faixa_premio', models.CharField(blank=True, default='', max_length=100, verbose_name='Faixa de premiação')),
                ('concurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos_apostados', to='jogos.concurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to=settings.AUTH_USER_MODEL)),
                ('tipo_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_gerados', to='jogos.tipojogo')),
            ],
            options={
                'verbose_name': 'Jogo Gerado',
                'verbose_name_plural': 'Jogos Gerados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='concurso',
            name='tipo_jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concursos', to='jogos.tipojogo'),
        ),
        migrations.AlterUniqueTogether(
            name='concurso',
            unique_together={('tipo_jogo', 'numero')},
        ),
    ]
