# Generated by Django 5.0.6 on 2026-09-08 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('contest', models.CharField(max_length=20, verbose_name='Concurso')),
                ('numbers', models.JSONField(verbose_name='Numeros sorteados')),
                ('clovers', models.JSONField(blank=True, default=list, verbose_name='Trevos sorteados')),
                ('prizes', models.JSONField(blank=True, default=dict, verbose_name='Premiacoes')),
                ('source', models.CharField(default='CEF', max_length=50, verbose_name='Origem')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Capturado em')),
            ],
            options={
                'verbose_name': 'Resultado Oficial',
                'verbose_name_plural': 'Resultados Oficiais',
                'ordering': ['-captured_at'],
                'unique_together': {('game', 'contest')},
            },
        ),
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('total_bets', models.PositiveIntegerField(default=0, verbose_name='Total de Jogos')),
                ('total_with_sequence', models.PositiveIntegerField(default=0, verbose_name='Jogos com Sequencia')),
                ('total_without_sequence', models.PositiveIntegerField(default=0, verbose_name='Jogos sem Sequencia')),
                ('most_frequent_numbers', models.JSONField(default=list, verbose_name='Numeros Mais Frequentes')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualizacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estatistica',
                'verbose_name_plural': 'Estatisticas',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('contest', models.CharField(max_length=20, verbose_name='Concurso')),
                ('numbers', models.JSONField(verbose_name='Numeros')),
                ('clovers', models.JSONField(blank=True, default=list, verbose_name='Trevos')),
                ('sequential_pairs', models.PositiveIntegerField(default=0, verbose_name='Pares Sequenciais')),
                ('manual', models.BooleanField(default=False, verbose_name='Jogo Manual')),
                ('result_checked', models.BooleanField(default=False, verbose_name='Resultado verificado')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Acertos')),
                ('prize', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Premio')),
                ('prize_description', models.CharField(blank=True, default='', max_length=120, verbose_name='Descricao do premio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Jogo Gerado',
                'verbose_name_plural': 'Jogos Gerados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'game'], name='loterias_co_user_id_f7fe95_idx'), models.Index(fields=['created_at'], name='loterias_co_created_7816b1_idx')],
            },
        ),
    ]
