# Generated by Django 6.0.5 on 2026-09-02 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLoteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('concurso', models.CharField(max_length=20, verbose_name='Concurso')),
                ('numeros', models.JSONField(verbose_name='Numeros sorteados')),
                ('trevos', models.JSONField(blank=True, default=list, verbose_name='Trevos sorteados')),
                ('premiacoes', models.JSONField(blank=True, default=dict, verbose_name='Premiacoes')),
                ('origem', models.CharField(default='CEF', max_length=50, verbose_name='Origem')),
                ('capturado_em', models.DateTimeField(auto_now_add=True, verbose_name='Capturado em')),
            ],
            options={
                'verbose_name': 'Resultado Oficial',
                'verbose_name_plural': 'Resultados Oficiais',
                'ordering': ['-capturado_em'],
                'unique_together': {('jogo', 'concurso')},
            },
        ),
        migrations.CreateModel(
            name='EstatisticaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('total_jogos', models.PositiveIntegerField(default=0, verbose_name='Total de Jogos')),
                ('total_com_sequencia', models.PositiveIntegerField(default=0, verbose_name='Jogos com Sequencia')),
                ('total_sem_sequencia', models.PositiveIntegerField(default=0, verbose_name='Jogos sem Sequencia')),
                ('numero_mais_frequente', models.JSONField(default=list, verbose_name='Numeros Mais Frequentes')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualizacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estatistica',
                'verbose_name_plural': 'Estatisticas',
                'unique_together': {('usuario', 'jogo')},
            },
        ),
        migrations.CreateModel(
            name='JogoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('concurso', models.CharField(max_length=20, verbose_name='Concurso')),
                ('numeros', models.JSONField(verbose_name='Numeros')),
                ('trevos', models.JSONField(blank=True, default=list, verbose_name='Trevos')),
                ('pares_sequenciais', models.PositiveIntegerField(default=0, verbose_name='Pares Sequenciais')),
                ('manual', models.BooleanField(default=False, verbose_name='Jogo Manual')),
                ('resultado_verificado', models.BooleanField(default=False, verbose_name='Resultado verificado')),
                ('acertos', models.PositiveIntegerField(default=0, verbose_name='Acertos')),
                ('premio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Premio')),
                ('premio_descricao', models.CharField(blank=True, default='', max_length=120, verbose_name='Descricao do premio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Jogo Gerado',
                'verbose_name_plural': 'Jogos Gerados',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'jogo'], name='loterias_co_usuario_fa32da_idx'), models.Index(fields=['criado_em'], name='loterias_co_criado__e1b632_idx')],
            },
        ),
    ]
