# Generated by Django 5.0.6 on 2026-09-09 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterias_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField(default=False, verbose_name='Premiado')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('bet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='loterias_core.generatedbet', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Notificacao de Acerto',
                'verbose_name_plural': 'Notificacoes de Acerto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read'], name='loterias_co_is_read_4d03fc_idx')],
            },
        ),
    ]
