# Generated by Django 5.0.6 on 2026-09-09 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterias_core', '0002_hitnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_enabled', models.BooleanField(default=True, verbose_name='Aviso no site')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Aviso por e-mail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificacao',
                'verbose_name_plural': 'Preferencias de Notificacao',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.CheckConstraint(check=models.Q(('site_enabled', True), ('email_enabled', True), _connector='OR'), name='notificationpreference_at_least_one_channel_enabled'),
        ),
    ]
