# Generated by Django 5.0.6 on 2026-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterias_core', '0003_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('hits', models.PositiveIntegerField(verbose_name='Acertos')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('winners', models.PositiveIntegerField(default=0, verbose_name='Ganhadores')),
                ('reference_month', models.DateField(verbose_name='Mes de Referencia')),
            ],
            options={
                'verbose_name': 'Faixa de Premiacao',
                'verbose_name_plural': 'Faixas de Premiacao',
                'ordering': ['-reference_month'],
                'unique_together': {('game', 'hits', 'reference_month')},
            },
        ),
    ]
