# Generated by Django 5.0.6 on 2026-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterias_core', '0004_prizetier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureFailureAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('contest', models.CharField(max_length=20, verbose_name='Concurso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Alerta de Falha de Captura',
                'verbose_name_plural': 'Alertas de Falha de Captura',
                'unique_together': {('game', 'contest')},
            },
        ),
    ]
