# Generated by Django 5.0.6 on 2026-09-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterias_core', '0005_capturefailurealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryresult',
            name='numbers_second_draw',
            field=models.JSONField(blank=True, default=list, verbose_name='Numeros sorteados (2o sorteio)'),
        ),
        migrations.AddField(
            model_name='lotteryresult',
            name='prizes_second_draw',
            field=models.JSONField(blank=True, default=dict, verbose_name='Premiacoes (2o sorteio)'),
        ),
    ]
