# Generated by Django 5.0.6 on 2026-09-18 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterias_core', '0006_lotteryresult_numbers_second_draw_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('Mega-sena', 'Mega-sena'), ('Milionaria', 'Milionaria'), ('Lotomania', 'Lotomania'), ('Lotofacil', 'Lotofacil'), ('Quina', 'Quina'), ('Dupla-Sena', 'Dupla-Sena')], max_length=20, verbose_name='Jogo')),
                ('rule_name', models.CharField(choices=[('limit_sequence_count', 'Limita quantidade de números em sequência'), ('limit_sequence_pairs', 'Limita quantidade de sequências num jogo'), ('limit_row_count', 'Limita quantidade de números na mesma linha do volante'), ('limit_column_count', 'Limita quantidade de números na mesma coluna do volante'), ('distribution_type', 'Tipo de distribuição'), ('limit_min_gap_between_sequences', 'Distância mínima entre sequências'), ('limit_min_sequences', 'Quantidade mínima de sequências')], max_length=40, verbose_name='Regra')),
                ('enabled', models.BooleanField(default=False, verbose_name='Ligada')),
                ('numeric_value', models.IntegerField(blank=True, null=True, verbose_name='Valor numerico')),
                ('choice_value', models.CharField(blank=True, max_length=30, null=True, verbose_name='Valor de escolha')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_rules', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Regra de Geracao',
                'verbose_name_plural': 'Regras de Geracao',
            },
        ),
        migrations.AddConstraint(
            model_name='generationrule',
            constraint=models.CheckConstraint(check=models.Q(('choice_value__isnull', False), ('numeric_value__isnull', False), _negated=True), name='generationrule_not_both_numeric_and_choice_value'),
        ),
        migrations.AlterUniqueTogether(
            name='generationrule',
            unique_together={('user', 'game', 'rule_name')},
        ),
    ]
