# Generated by Django 5.0.6 on 2026-09-25 14:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loterias_core', '0007_generationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrule',
            name='numeric_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor numerico'),
        ),
        migrations.AddConstraint(
            model_name='generationrule',
            constraint=models.CheckConstraint(check=models.Q(('numeric_value__isnull', True), ('numeric_value__gte', 1), _connector='OR'), name='generationrule_numeric_value_at_least_one'),
        ),
    ]
